### ISSUE TITLE
Compiling error when try to build source on Ubuntu17.10?

### ISSUE THREAD

**Issue by abewangm** [goatpig/BitcoinArmory#447]
Was the source haven't compatible on latest compiler version on Ubuntu17.10? I follow the guild from official website to set up build environment. 
 
TransactionBatch.h:190:16: error: ‘function’ was not declared in this scope
------------------------------------------------------------------------------------------------------
make[3]: Entering directory '/home/meng/bitcoinarmory/source/BitcoinArmory/cppForSwig'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..    -O2 -std=c++11 -Ilmdb -Icryptopp -I/usr/include/python2.7  -D__STDC_LIMIT_MACROS -O2 -MT libCppBlockUtils_la-TransactionBatch.lo -MD -MP -MF .deps/libCppBlockUtils_la-TransactionBatch.Tpo -c -o libCppBlockUtils_la-TransactionBatch.lo `test -f 'TransactionBatch.cpp' || echo './'`TransactionBatch.cpp
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -O2 -std=c++11 -Ilmdb -Icryptopp -I/usr/include/python2.7 -D__STDC_LIMIT_MACROS -O2 -MT libCppBlockUtils_la-TransactionBatch.lo -MD -MP -MF .deps/libCppBlockUtils_la-TransactionBatch.Tpo -c TransactionBatch.cpp  -fPIC -DPIC -o .libs/libCppBlockUtils_la-TransactionBatch.o
In file included from TransactionBatch.cpp:9:0:
TransactionBatch.h:190:16: error: ‘function’ was not declared in this scope
    map<string, function<
                ^~~~~~~~
TransactionBatch.h:190:16: note: suggested alternative: ‘union’
    map<string, function<
                ^~~~~~~~
                union
TransactionBatch.h:191:60: error: expression list treated as compound expression in functional cast [-fpermissive]
       void(const vector<string>&, pair<unsigned, unsigned>&)> > sections_;
                                                            ^
TransactionBatch.h:191:61: error: template argument 2 is invalid
       void(const vector<string>&, pair<unsigned, unsigned>&)> > sections_;
                                                             ^
TransactionBatch.h:191:61: error: template argument 4 is invalid
TransactionBatch.h:191:63: error: expected unqualified-id before ‘>’ token
       void(const vector<string>&, pair<unsigned, unsigned>&)> > sections_;
                                                               ^
TransactionBatch.cpp: In constructor ‘TransactionBatch::TransactionBatch()’:
TransactionBatch.cpp:44:4: error: ‘sections_’ was not declared in this scope
    sections_.insert(make_pair(SECTION_WALLET, wallet_lbd));
    ^~~~~~~~~
TransactionBatch.cpp:44:4: note: suggested alternative: ‘setns’
    sections_.insert(make_pair(SECTION_WALLET, wallet_lbd));
    ^~~~~~~~~
    setns
TransactionBatch.cpp: In member function ‘void TransactionBatch::unserialize(const string&)’:
TransactionBatch.cpp:110:26: error: ‘sections_’ was not declared in this scope
       auto sectionIter = sections_.find(thisLine);
                          ^~~~~~~~~
TransactionBatch.cpp:110:26: note: suggested alternative: ‘sectionMap’
       auto sectionIter = sections_.find(thisLine);
                          ^~~~~~~~~
                          sectionMap
TransactionBatch.cpp:140:26: error: ‘sections_’ was not declared in this scope
       auto sectionIter = sections_.find(sectionPair.first);
                          ^~~~~~~~~
TransactionBatch.cpp:140:26: note: suggested alternative: ‘sectionMap’
       auto sectionIter = sections_.find(sectionPair.first);
                          ^~~~~~~~~
                          sectionMap
Makefile:864: recipe for target 'libCppBlockUtils_la-TransactionBatch.lo' failed
make[3]: *** [libCppBlockUtils_la-TransactionBatch.lo] Error 1
make[3]: Leaving directory '/home/meng/bitcoinarmory/source/BitcoinArmory/cppForSwig'
Makefile:1446: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/meng/bitcoinarmory/source/BitcoinArmory/cppForSwig'
Makefile:430: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/meng/bitcoinarmory/source/BitcoinArmory'
Makefile:362: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by goatpig** [comment]
What branch/tag are you on?

**Comment by abewangm** [comment]
git checkout v0.96.

**Comment by goatpig** [comment]
pull master or testing

**Comment by abewangm** [comment]
master branch source works on Ubuntu 17.10 with apt-get pulled GCC version. appreciate the quick response.
