### ISSUE TITLE
Unable to open receive bitcoins

### ISSUE THREAD

**Issue by c-kr** [goatpig/BitcoinArmory#229]
After updating to 0.96 I am unable to open the receive bitcoin dialog with one wallet. another wallet on the same machine is working.
```
Traceback (most recent call last):
  File "/usr/local/lib/armory/qtdialogs.py", line 1541, in getNewAddress
    if showRecvCoinsWarningIfNecessary(self.wlt, self, self.main):
  File "/usr/local/lib/armory/qtdialogs.py", line 2062, in showRecvCoinsWarningIfNecessary
    result = MsgBoxWithDNAA(parent, main, parent.Warning, parent.tr('This is not your wallet!'), parent.tr(
AttributeError: 'DlgWalletDetails' object has no attribute 'Warning'
```

**Comment by goatpig** [comment]
Fixed in the next:

https://github.com/goatpig/BitcoinArmory/releases/tag/v0.96.0.1-testing
